BB#!/bin/zsh

# Set default browser to firefox
export BROWSER="firefox"

# Set editor to vim
export EDITOR="emacs"

# java fix
#wmname LG3D &

# Merge xresources
xrdb -merge /home/ahmed/.Xresources

# Set danish keyboard layout
#setxkbmap -layout dk

# Set x cursor to something more... Appropriate
xsetroot -cursor_name left_ptr

# Let Canto refresh it's feeds (NOTE: Doesn't need an ampersand, the command
# is a daemon itself)
#canto-fetch -b

# Start Emacs as a daemon (NOTE: Doesn't need an ampersand, the command is a
# daemon itself)
#emacs --daemon

# unclutter to hide the cursor
#unclutter -idle 2 &

# Start xcompmgr
xcompmgr -c &

# Start the Dropbox daemon
#/usr/bin/dropboxd &

# Uses feh to set the background
sh /home/ahmed/.config/wallpaper.sh &

exec subtle

#case $1 in
#i3)
#	exec i3
#	;;
#dwm)
#	# conky
#	conky | while read -r; do xsetroot -name "$REPLY"; done &
#	exec dwm
#	;;
#esac
