# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="honukai"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/home/user/go/bin"
export GOPATH="/home/user/go"
export JAVA_HOME="/usr/lib/jvm/default/"

# alias
alias c='clear'
alias ..='cd ..'

## pacman/aur wrapper commands
alias search='pacman -Ss'
alias install='sudo pacman -S'
alias remove='sudo pacman -Rncs'
alias update='sudo pacman -Syy'
alias upgrade='sudo pacman -Su'

alias asearch='apacman -Ss'
alias ainstall='apacman -S'
alias aremove='apacman -Rncs'
alias aupdate='apacman -Syy'
alias aupgrade='apacman -Su'

alias nukepkg='sudo pacman -Rns $(pacman -Qtdq)'

## git
alias gitstatus='find . -type d -name ".git" | while read dir ; do sh -c "cd $dir/../ && git status -s | grep 
-q [azAZ09] && echo -------- ${dir//\.git/} -------- && git status -s" ; done'

# Something for the PIP
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.
