#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Set default browser to Opera
#export BROWSER="opera"

# Change your keymap:
#xmodmap "/home/ahmed/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
xcompmgr -c &
unclutter -idle 2 &
xfce4-power-manager &
pnmixer &
sh /home/ahmed/wallpaper.sh &
exec ck-launch-session nm-applet &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec ck-launch-session dbus-launch fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/ahmed/.fluxbox/log"
